service: simple-aws-lambda

provider:
  name: aws
  runtime: java8
  region: us-east-1
  timeout: 10
  memorySize: 1024
  apiGateway:
    binaryMediaTypes:
      - '*/*'

package:
  artifact: target/lambda.helm-1.0-SNAPSHOT.jar

functions:
  simpleHttp:
    handler: com.ishchenko.artem.helm.StreamLambdaHandler::handleRequest
    events:
      - http:
          method: GET
          path: /
      - http:
          method: POST
          path: /simple
          contentHandling: CONVERT_TO_BINARY
