name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*', master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and verify
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
            - name: Build with Maven
              run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
                -Dsonar.host.url=https://sonarcloud.io
                -Dsonar.organization=$ORGANIZATION
                -Dsonar.projectKey=$PROJECT_KEY
                -Dsonar.login=$SONAR_TOKEN
                -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                ORGANIZATION: chronicle-team
                PROJECT_KEY: helm-host
